from datetime import datetime
from pathlib import Path

import pandas as pd

from django.contrib.auth.models import User
from django.core.management.base import BaseCommand


class Command(BaseCommand):
    help = "Update and create new Login Profiles "

    def handle(self, *args, **kwargs):

        from crawl.external_party_communication_facilitator import create_workflow_from_payload,queue_vivid_mind_payload
        print('yes')
        payload = {
            "action": "create",
            "id": 1,
            "name": "Spread Awareness in Cave Creek Arizona--IG  Android",
            "service": "instagram",
            "customer": 1,
            "activity_to_perform": "like,follow,comment",
            "os": "android",
            "localstore": False,
            "proxy_disable": True,
            "blacklist": "",
            "required_interactions": 10000,
            "launch_datetime": None,
            "stop_datetime": None,
            "internal_state": "active",
            "campaign_state": "launched",
            "is_completed": False,
            "is_deleted": False,
            "media_id": None,
            "comment_id": None,
            "childbots": [
                {
                    "id": 1,
                    "display_name": "always_julian.camarena",
                    "device": "N7GV460108",
                    "service": "instagram",
                    "customer": 1,
                    "username": "always_julian.camarena",
                    "password": "koolboy@1",
                    "phone_number": None,
                    "email_address": "always_julian.camarena@datatrader.space",
                    "email_password": None,
                    "recovery_email": None,
                    "imap_email_host": None,
                    "imap_email_username": None,
                    "imap_email_password": None,
                    "imap_email_port": None,
                    "followers": 0,
                    "following": 0,
                    "post_count": 0,
                    "profile_picture": None,
                    "dob": None,
                    "bio": "",
                    "first_name": None,
                    "last_name": None,
                    "email_provider": 2,
                    "state": "active",
                },
                {
                    "id": 2,
                    "display_name": "martinez_cooporation_limited",
                    "device": "N7GV460108",
                    "service": "instagram",
                    "customer": 1,
                    "username": "martinez_cooporation_limited",
                    "password": "asdf#6868",
                    "phone_number": None,
                    "email_address": "ernestmartinez2734@eazymail.club",
                    "email_password": None,
                    "recovery_email": None,
                    "imap_email_host": None,
                    "imap_email_username": None,
                    "imap_email_password": None,
                    "imap_email_port": None,
                    "followers": 0,
                    "following": 0,
                    "post_count": 0,
                    "profile_picture": None,
                    "dob": None,
                    "bio": "",
                    "first_name": None,
                    "last_name": None,
                    "email_provider": None,
                    "state": "active",
                },
                {
                    "id": 3,
                    "display_name": "jeffreylong16",
                    "device": "ZY22F82FWS",
                    "service": "instagram",
                    "customer": 1,
                    "username": "jeffreylong16",
                    "password": "asdf#6868",
                    "phone_number": None,
                    "email_address": "jeffreylong16@eazymail.club",
                    "email_password": None,
                    "recovery_email": None,
                    "imap_email_host": None,
                    "imap_email_username": None,
                    "imap_email_password": None,
                    "imap_email_port": None,
                    "followers": 0,
                    "following": 0,
                    "post_count": 0,
                    "profile_picture": None,
                    "dob": None,
                    "bio": "",
                    "first_name": None,
                    "last_name": None,
                    "email_provider": None,
                    "state": "active",
                },
                {
                    "id": 6,
                    "display_name": "tiffanypearson969",
                    "device": "ZY22F82FWS",
                    "service": "instagram",
                    "customer": 1,
                    "username": "tiffanypearson969",
                    "password": "f9ud>aLp",
                    "phone_number": None,
                    "email_address": "tiffanypearson969@eazymail.club",
                    "email_password": None,
                    "recovery_email": None,
                    "imap_email_host": None,
                    "imap_email_username": None,
                    "imap_email_password": None,
                    "imap_email_port": None,
                    "followers": 0,
                    "following": 0,
                    "post_count": 0,
                    "profile_picture": None,
                    "dob": None,
                    "bio": "",
                    "first_name": None,
                    "last_name": None,
                    "email_provider": None,
                    "state": "active",
                },
                {
                    "id": 13,
                    "display_name": "rusticlandscapedecor",
                    "device": "ZY22F82FWS",
                    "service": "instagram",
                    "customer": 1,
                    "username": "rusticlandscapedecor",
                    "password": "miguel909",
                    "phone_number": None,
                    "email_address": "camarena_fans_forever@datatrader.space",
                    "email_password": None,
                    "recovery_email": None,
                    "imap_email_host": None,
                    "imap_email_username": None,
                    "imap_email_password": None,
                    "imap_email_port": None,
                    "followers": 0,
                    "following": 0,
                    "post_count": 0,
                    "profile_picture": None,
                    "dob": None,
                    "bio": "",
                    "first_name": None,
                    "last_name": None,
                    "email_provider": 2,
                    "state": "active",
                },
                {
                    "id": 14,
                    "display_name": "SouthwestSplendor",
                    "device": "ZY22F82FWS",
                    "service": "instagram",
                    "customer": 1,
                    "username": "SouthwestSplendor",
                    "password": "plint893",
                    "phone_number": None,
                    "email_address": "we.love_juliancamarena@datatrader.space",
                    "email_password": None,
                    "recovery_email": None,
                    "imap_email_host": None,
                    "imap_email_username": None,
                    "imap_email_password": None,
                    "imap_email_port": None,
                    "followers": 0,
                    "following": 0,
                    "post_count": 0,
                    "profile_picture": None,
                    "dob": None,
                    "bio": "",
                    "first_name": None,
                    "last_name": None,
                    "email_provider": 2,
                    "state": "active",
                },
                {
                    "id": 15,
                    "display_name": "NativeHeritageDecor",
                    "device": "ZY22F82FWS",
                    "service": "instagram",
                    "customer": 1,
                    "username": "NativeHeritageDecor",
                    "password": "coolie@1234",
                    "phone_number": None,
                    "email_address": "juliancamarena_love@datatrader.space",
                    "email_password": None,
                    "recovery_email": None,
                    "imap_email_host": None,
                    "imap_email_username": None,
                    "imap_email_password": None,
                    "imap_email_port": None,
                    "followers": 0,
                    "following": 0,
                    "post_count": 0,
                    "profile_picture": None,
                    "dob": None,
                    "bio": "",
                    "first_name": None,
                    "last_name": None,
                    "email_provider": 2,
                    "state": "active",
                },
            ],
            "devices": [
                {
                    "id": 1,
                    "name": "moto11",
                    "serial_number": "ZY22F82FWS",
                    "info": None,
                    "connected_to_server": 3,
                },
                {
                    "id": 2,
                    "name": "moto12",
                    "serial_number": "N7GV460108",
                    "info": None,
                    "connected_to_server": 3,
                },
            ],
            "scrape_tasks": [
                {
                    "id": 2,
                    "service": "instagram",
                    "customer": 1,
                    "name": "scrape_cave_creek_arizona_database",
                    "internal_state": "active",
                    "input": "location_posts__213190018",
                    "os": "browser",
                    "localstore": False,
                    "threading": False,
                    "childbots": [
                        {
                            "id": 1,
                            "display_name": "always_julian.camarena",
                            "device": "N7GV460108",
                            "service": "instagram",
                            "customer": 1,
                            "username": "always_julian.camarena",
                            "password": "koolboy@1",
                            "phone_number": None,
                            "email_address": "always_julian.camarena@datatrader.space",
                            "email_password": None,
                            "recovery_email": None,
                            "imap_email_host": None,
                            "imap_email_username": None,
                            "imap_email_password": None,
                            "imap_email_port": None,
                            "followers": 0,
                            "following": 0,
                            "post_count": 0,
                            "profile_picture": None,
                            "dob": None,
                            "bio": "",
                            "first_name": None,
                            "last_name": None,
                            "email_provider": 2,
                            "state": "active",
                        },
                        {
                            "id": 2,
                            "display_name": "martinez_cooporation_limited",
                            "device": "N7GV460108",
                            "service": "instagram",
                            "customer": 1,
                            "username": "martinez_cooporation_limited",
                            "password": "asdf#6868",
                            "phone_number": None,
                            "email_address": "ernestmartinez2734@eazymail.club",
                            "email_password": None,
                            "recovery_email": None,
                            "imap_email_host": None,
                            "imap_email_username": None,
                            "imap_email_password": None,
                            "imap_email_port": None,
                            "followers": 0,
                            "following": 0,
                            "post_count": 0,
                            "profile_picture": None,
                            "dob": None,
                            "bio": "",
                            "first_name": None,
                            "last_name": None,
                            "email_provider": None,
                            "state": "active",
                        },
                        {
                            "id": 3,
                            "display_name": "jeffreylong16",
                            "device": "ZY22F82FWS",
                            "service": "instagram",
                            "customer": 1,
                            "username": "jeffreylong16",
                            "password": "asdf#6868",
                            "phone_number": None,
                            "email_address": "jeffreylong16@eazymail.club",
                            "email_password": None,
                            "recovery_email": None,
                            "imap_email_host": None,
                            "imap_email_username": None,
                            "imap_email_password": None,
                            "imap_email_port": None,
                            "followers": 0,
                            "following": 0,
                            "post_count": 0,
                            "profile_picture": None,
                            "dob": None,
                            "bio": "",
                            "first_name": None,
                            "last_name": None,
                            "email_provider": None,
                            "state": "active",
                        },
                        {
                            "id": 6,
                            "display_name": "tiffanypearson969",
                            "device": "ZY22F82FWS",
                            "service": "instagram",
                            "customer": 1,
                            "username": "tiffanypearson969",
                            "password": "f9ud>aLp",
                            "phone_number": None,
                            "email_address": "tiffanypearson969@eazymail.club",
                            "email_password": None,
                            "recovery_email": None,
                            "imap_email_host": None,
                            "imap_email_username": None,
                            "imap_email_password": None,
                            "imap_email_port": None,
                            "followers": 0,
                            "following": 0,
                            "post_count": 0,
                            "profile_picture": None,
                            "dob": None,
                            "bio": "",
                            "first_name": None,
                            "last_name": None,
                            "email_provider": None,
                            "state": "active",
                        },
                        {
                            "id": 13,
                            "display_name": "rusticlandscapedecor",
                            "device": "ZY22F82FWS",
                            "service": "instagram",
                            "customer": 1,
                            "username": "rusticlandscapedecor",
                            "password": "miguel909",
                            "phone_number": None,
                            "email_address": "camarena_fans_forever@datatrader.space",
                            "email_password": None,
                            "recovery_email": None,
                            "imap_email_host": None,
                            "imap_email_username": None,
                            "imap_email_password": None,
                            "imap_email_port": None,
                            "followers": 0,
                            "following": 0,
                            "post_count": 0,
                            "profile_picture": None,
                            "dob": None,
                            "bio": "",
                            "first_name": None,
                            "last_name": None,
                            "email_provider": 2,
                            "state": "active",
                        },
                        {
                            "id": 14,
                            "display_name": "SouthwestSplendor",
                            "device": "ZY22F82FWS",
                            "service": "instagram",
                            "customer": 1,
                            "username": "SouthwestSplendor",
                            "password": "plint893",
                            "phone_number": None,
                            "email_address": "we.love_juliancamarena@datatrader.space",
                            "email_password": None,
                            "recovery_email": None,
                            "imap_email_host": None,
                            "imap_email_username": None,
                            "imap_email_password": None,
                            "imap_email_port": None,
                            "followers": 0,
                            "following": 0,
                            "post_count": 0,
                            "profile_picture": None,
                            "dob": None,
                            "bio": "",
                            "first_name": None,
                            "last_name": None,
                            "email_provider": 2,
                            "state": "active",
                        },
                        {
                            "id": 15,
                            "display_name": "NativeHeritageDecor",
                            "device": "ZY22F82FWS",
                            "service": "instagram",
                            "customer": 1,
                            "username": "NativeHeritageDecor",
                            "password": "coolie@1234",
                            "phone_number": None,
                            "email_address": "juliancamarena_love@datatrader.space",
                            "email_password": None,
                            "recovery_email": None,
                            "imap_email_host": None,
                            "imap_email_username": None,
                            "imap_email_password": None,
                            "imap_email_port": None,
                            "followers": 0,
                            "following": 0,
                            "post_count": 0,
                            "profile_picture": None,
                            "dob": None,
                            "bio": "",
                            "first_name": None,
                            "last_name": None,
                            "email_provider": 2,
                            "state": "active",
                        },
                    ],
                }
            ],
            "messaging": [
                {
                    "id": 1,
                    "name": None,
                    "comment_list": "",
                    "influencer_profile": "",
                    "welcome_message": "",
                    "followup_message": "",
                    "reachout_message": "",
                    "response_to_reachout_message": "",
                    "target_hashtag": "",
                    "target_location": None,
                    "message_list": "",
                },
                {
                    "id": 2,
                    "name": "Latest Collection-Promotion-for-CC Audience",
                    "comment_list": "Captivating desert sunsets meet stunning art - explore our latest exhibition!\r\nFavorite desert art style? Share your thoughts!\r\nPeek behind the scenes of our next exhibition!\r\nMeet @featured_artist, a rising Cave Creek star!\r\nDon't miss the @local_art_event showcasing our incredible artists!",
                    "influencer_profile": "",
                    "welcome_message": "Hi! Welcome to our Art Gallery, Enjoy 20% discount on our new Collection. Link in bio",
                    "followup_message": "",
                    "reachout_message": "Calling all desert art lovers! ✨ Immerse yourself in the breathtaking landscapes of [artist name]'s new exhibition at [gallery name] now. Open [days/times]. Can't wait to see you there! #CaveCreekArt",
                    "response_to_reachout_message": "",
                    "target_hashtag": "",
                    "target_location": None,
                    "message_list": "",
                },
            ],
            "sharing": [
                {
                    "id": 1,
                    "name": "Share_latest_collection_post_1",
                    "link": "http://somelink.com",
                    "target_posts": None,
                }
            ],
            "settings": [
                {
                    "id": 1,
                    "name": "Usual_Settings",
                    "start_time": None,
                    "expires": None,
                    "delay_range": None,
                    "max_interactions_per_runtask": 5,
                    "delay_between_runtasks": 1,
                    "behavior": {
                        "with_new_followers": "welocome_message,like_3,comment_3,share_post",
                        "with_target": "follow",
                        "with_liker": "like",
                        "with_commenter": "like_comment",
                        "follow_per_session": 10,
                    },
                    "max_scrape_bots": 2,
                }
            ],
        }
        #queue_vivid_mind_payload(payload)
        create_workflow_from_payload()
