# Generated by Django 3.2 on 2025-01-31 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0007_auto_20250131_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 19, 50, 59, 937125), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 19, 50, 59, 945237)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='c8fcb106-dfe2-11ef-b28d-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='c8fcb106-dfe2-11ef-b28d-047c1611323a', max_length=50000, unique=True),
        ),
    ]
