# Generated by Django 3.2 on 2025-01-31 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0008_auto_20250131_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 22, 38, 28, 701453), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 31, 22, 38, 28, 701453)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(default=models.CharField(default='2e844a84-dffa-11ef-9df2-047c1611323a', max_length=50000, unique=True), max_length=5000),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='2e844a84-dffa-11ef-9df2-047c1611323a', max_length=50000, unique=True),
        ),
    ]
