# Generated by Django 3.2 on 2025-02-15 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0010_auto_20250212_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrecord',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 22, 32, 46, 229374), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 15, 22, 32, 46, 229374)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='de9572f3-ebc2-11ef-9b2e-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='de9572f3-ebc2-11ef-9b2e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
