# Generated by Django 3.2 on 2025-02-18 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0011_auto_20250215_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestrecord',
            name='run_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 14, 45, 3, 181764), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 14, 45, 3, 188804)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='06f19e52-eddd-11ef-9461-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='06f19e52-eddd-11ef-9461-047c1611323a', max_length=50000, unique=True),
        ),
    ]
