# Generated by Django 5.1.6 on 2025-03-08 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0012_auto_20250218_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childbot',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'twitter'), ('threads', 'threads'), ('tiktok', 'tiktok'), ('facebook', 'facebook'), ('cleaner', 'cleaner'), ('reports_manager', 'reports_manager'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse'), ('daraz', 'Daraz.pk')], db_index=True, default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicereport',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'twitter'), ('threads', 'threads'), ('tiktok', 'tiktok'), ('facebook', 'facebook'), ('cleaner', 'cleaner'), ('reports_manager', 'reports_manager'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse'), ('daraz', 'Daraz.pk')], max_length=20),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 0, 51, 23, 591065), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 9, 0, 51, 23, 594063)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='b6cb0706-fc56-11ef-84a6-408d5cc49b7c', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='service',
            field=models.CharField(choices=[('instagram', 'Instagram'), ('twitter', 'twitter'), ('threads', 'threads'), ('tiktok', 'tiktok'), ('facebook', 'facebook'), ('cleaner', 'cleaner'), ('reports_manager', 'reports_manager'), ('data_enricher', 'Data Enricher'), ('openai', 'OpenAI'), ('audience', 'Audience'), ('datahouse', 'DataHouse'), ('daraz', 'Daraz.pk')], db_index=True, default='instagram', max_length=50),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='b6cb0706-fc56-11ef-84a6-408d5cc49b7c', max_length=50000, unique=True),
        ),
    ]
