# Generated by Django 3.2 on 2025-03-27 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0013_alter_childbot_service_alter_devicereport_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='excluded_queries',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='failed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='success_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 18, 36, 16, 290715), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 18, 36, 16, 298206)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='753eddca-0b10-11f0-8bd4-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='753eddca-0b10-11f0-8bd4-047c1611323a', max_length=50000, unique=True),
        ),
    ]
