# Generated by Django 3.2 on 2025-03-27 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0014_auto_20250327_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='excluded_queries',
        ),
        migrations.AddField(
            model_name='task',
            name='blacklisted_usernames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='consumed_usernames',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 18, 42, 47, 106078), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 27, 18, 42, 47, 113613)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='5e307c40-0b11-11f0-ab8c-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='5e307c40-0b11-11f0-ab8c-047c1611323a', max_length=50000, unique=True),
        ),
    ]
