# Generated by Django 5.1.6 on 2025-05-02 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0015_auto_20250327_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 23, 5, 46, 728703), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 2, 23, 5, 46, 731704)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='1272d10b-2780-11f0-bffa-408d5cc49b7c', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='1272d10b-2780-11f0-bffa-408d5cc49b7c', max_length=50000, unique=True),
        ),
    ]
