# Generated by Django 3.2 on 2025-05-03 10:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0016_alter_interaction_interaction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 15, 8, 29, 235222), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 3, 15, 8, 29, 245350)),
        ),
        migrations.AlterField(
            model_name='task',
            name='os',
            field=models.CharField(blank=True, choices=[('android', 'android'), ('browser', 'browser')], max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='8f95dd95-2806-11f0-975e-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='8f95dd95-2806-11f0-975e-047c1611323a', max_length=50000, unique=True),
        ),
    ]
