# Generated by Django 5.2 on 2025-05-16 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0017_auto_20250503_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='activity',
            field=models.CharField(choices=[('dm', 'DM'), ('follow', 'Follow'), ('like', 'Like'), ('watch_story', 'WatchStory')], max_length=500),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 21, 7, 12, 252980), null=True),
        ),
        
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 21, 7, 12, 255069)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='d3ac791f-326f-11f0-86ae-047c1611323a', max_length=50000, unique=True)),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='d3ac791f-326f-11f0-86ae-047c1611323a', max_length=50000, unique=True),
        ),
    ]
