# Generated by Django 5.2 on 2025-05-16 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0018_alter_interaction_activity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 21, 7, 56, 940509), null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='ref_id',
            field=models.CharField(blank=True, null=True, verbose_name='Automation Task Id'),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 21, 7, 56, 942518)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='ee4f18a6-326f-11f0-96d3-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='ee4f18a6-326f-11f0-96d3-047c1611323a', max_length=50000, unique=True),
        ),
    ]
