# Generated by Django 5.2 on 2025-05-16 16:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0019_alter_interaction_interaction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 9, 17, 53, 226094), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 16, 9, 17, 53, 228603)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='51b90e55-3271-11f0-ba1e-b81ea4842696', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='51b90e55-3271-11f0-ba1e-b81ea4842696', max_length=50000, unique=True),
        ),
    ]
