# Generated by Django 5.2 on 2025-05-30 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0020_alter_interaction_interaction_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_task_status', models.CharField(max_length=50)),
                ('report_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('report_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('total_task_runtime_text', models.CharField(max_length=100)),
                ('total_task_runtime_seconds', models.FloatField()),
                ('runs_initiated', models.IntegerField()),
                ('runs_completed', models.IntegerField()),
                ('runs_failed_exception', models.IntegerField()),
                ('runs_incomplete', models.IntegerField()),
                ('found_next_page_info_count', models.IntegerField()),
                ('next_page_info_not_found_count', models.IntegerField()),
                ('saved_file_count', models.IntegerField()),
                ('downloaded_file_count', models.IntegerField()),
                ('failed_download_count', models.IntegerField()),
                ('overall_bot_login_status', models.CharField(max_length=50)),
                ('last_status_of_task', models.CharField(max_length=255)),
                ('billing_issue_resolution_status', models.CharField(max_length=255)),
                ('scraped_data_summary', models.JSONField(default=dict)),
                ('non_fatal_errors_summary', models.TextField()),
                ('exceptions_summary', models.TextField()),
                ('specific_exception_reasons', models.TextField()),
                ('failed_downloads_summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 19, 30, 29, 96020), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 30, 19, 30, 29, 97021)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='a2815748-3d62-11f0-8152-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='a2815748-3d62-11f0-8152-047c1611323a', max_length=50000, unique=True),
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
