# Generated by Django 5.2 on 2025-06-09 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0021_taskanalysisreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskanalysisreport',
            name='data_enrichment_summary',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 9, 8, 24, 35, 484239), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 9, 8, 24, 35, 486384)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='446dabd9-44e1-11f0-a7bb-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='446dabd9-44e1-11f0-a7bb-047c1611323a', max_length=50000, unique=True),
        ),
    ]
