# Generated by Django 5.2.3 on 2025-06-30 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0022_taskanalysisreport_data_enrichment_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 16, 21, 36, 53875), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 6, 30, 16, 21, 36, 53875)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='624a9880-55a4-11f0-960d-2cfda172866f', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='624a9880-55a4-11f0-960d-2cfda172866f', max_length=50000, unique=True),
        ),
    ]
