# Generated by Django 5.1.7 on 2025-07-01 05:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0023_alter_interaction_interaction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 10, 22, 26, 655070), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 10, 22, 26, 658065)),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='604309b2-563b-11f0-b144-2cfda172866f', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='604309b2-563b-11f0-b144-2cfda172866f', max_length=50000, unique=True),
        ),
    ]
