# Generated by Django 5.1.7 on 2025-07-16 09:22

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0024_alter_interaction_interaction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 16, 14, 22, 16, 56955), null=True),
        ),
        migrations.AlterField(
            model_name='requestrecord',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='5d35c4d0-6226-11f0-b7fd-2cfda172866f', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='5d35c4d0-6226-11f0-b7fd-2cfda172866f', max_length=50000, unique=True),
        ),
    ]
