# Generated by Django 5.2.4 on 2025-08-05 08:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0025_alter_interaction_interaction_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 13, 9, 18, 780992), null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='7c699e10-71d3-11f0-9181-74563c02f7f7', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='7c699e10-71d3-11f0-9181-74563c02f7f7', max_length=50000, unique=True),
        ),
    ]
