# Generated by Django 3.2 on 2025-08-05 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0026_alter_interaction_interaction_time_alter_task_ref_id_and_more'),
    ]

    operations = [

        migrations.AlterField(
            model_name='task',
            name='add_data',
            field=models.JSONField(blank=True, default={'datahouse_blocks': '', 'datahouse_url': '', 'max_requests_per_bot': '100', 'max_requests_per_day': 200, 'max_requests_per_run': 5, 'max_threads': 10, 'reporting_house_url': '', 'save_to_storage_house': True}, null=True),
        )
    ]
