# Generated by Django 5.2.4 on 2025-08-05 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0027_auto_20250805_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interaction',
            name='interaction_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 5, 22, 38, 40, 701732), null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='ref_id',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Automation Task Id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='add_data',
            field=models.JSONField(blank=True, default={'datahouse_blocks': [], 'datahouse_url': '', 'max_requests_per_bot': '100', 'max_requests_per_day': 200, 'max_requests_per_run': 5, 'max_threads': 10, 'reporting_house_url': '', 'save_to_storage_house': True}, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='ref_id',
            field=models.CharField(blank=True, default=models.CharField(default='0680e36b-7223-11f0-9e87-047c1611323a', max_length=50000, unique=True), max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(default='0680e36b-7223-11f0-9e87-047c1611323a', max_length=50000, unique=True),
        ),
    ]
